export const RECEIVE_MY_CONTRACTS_SUCCESS = 'RECEIVE_MY_CONTRACTS_SUCCESS'
export const NEW_CONTRACT = 'NEW_CONTRACT'
export const JOIN_CONTRACT = 'JOIN_CONTRACT'
export const EXIT_CONTRACT = 'EXIT_CONTRACT'

export const CHANGE_CUSTOMER = 'CHANGE_CUSTOMER'
export const CHANGE_MERCHANT = 'CHANGE_MERCHANT'


